# Generated by Django 3.2.3 on 2022-10-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourteams', '0002_rename_winner_winnerpick_winningpicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='week_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='winningPicks',
            field=models.CharField(choices=[('Buffalo Bills', 'Buffalo Bills'), ('los Angeles Rams', 'los Angeles Rams')], max_length=250),
        ),
    ]
