# Generated by Django 3.2.3 on 2022-10-17 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yourteams', '0003_auto_20221016_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
