# Generated by Django 3.2.3 on 2022-10-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourteams', '0007_winnerpick_actual_winningpick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winnerpick',
            old_name='actual_winningPick',
            new_name='actual_winner',
        ),
        migrations.RenameField(
            model_name='winnerpick',
            old_name='winningPicks',
            new_name='selected_pick',
        ),
    ]
