# Generated by Django 3.2.3 on 2022-10-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourteams', '0008_auto_20221017_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerpick',
            name='status',
            field=models.CharField(choices=[('Win', 'Win'), ('Lose', 'Lose'), ('Tie', 'Tie')], max_length=6, null=True),
        ),
    ]
