# Generated by Django 3.2.3 on 2021-07-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_away',
            name='name',
            field=models.CharField(choices=[('Mom', 'Mom'), ('Mr. C.', 'Mr. C.'), ('Tiara', 'Tiara')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='home_away',
            name='awayteam',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='home_away',
            name='hometeam',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons')], default='', max_length=100),
        ),
    ]
