# Generated by Django 3.2.3 on 2021-07-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20210712_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_away',
            options={'ordering': ['-awayteam']},
        ),
        migrations.AlterField(
            model_name='home_away',
            name='awayteam',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Buffalo Bills', 'Buffalo Bills'), ('Chicago Bears', 'Chicago Bears'), ('dallas cowboys', 'Dallas Cowboys'), ('detroit lions', 'detroit lions'), ('green bay packers', 'green bay packers'), ('Houston Texans', 'houston texans')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='home_away',
            name='hometeam',
            field=models.CharField(choices=[('Arizona Cardinals', 'Arizona Cardinals'), ('Atlanta Falcons', 'Atlanta Falcons'), ('Buffalo Bills', 'Buffalo Bills'), ('Chicago Bears', 'Chicago Bears'), ('dallas cowboys', 'Dallas Cowboys'), ('detroit lions', 'detroit lions'), ('green bay packers', 'green bay packers'), ('Houston Texans', 'houston texans')], default='', max_length=100),
        ),
    ]
