# Generated by Django 3.2.3 on 2021-07-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20210714_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_away',
            name='name',
        ),
        migrations.AddField(
            model_name='home_away',
            name='week_number',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
