# Generated by Django 3.2.3 on 2021-11-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20211125_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_away',
            options={'ordering': ['-home_team', '-away_team']},
        ),
        migrations.RenameField(
            model_name='home_away',
            old_name='awayteam',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='home_away',
            old_name='hometeam',
            new_name='home_team',
        ),
    ]
