# Generated by Django 3.2.3 on 2022-09-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_auto_20220924_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_away',
            name='week_number',
            field=models.IntegerField(default=4),
        ),
    ]
