# Generated by Django 3.2.3 on 2022-10-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_auto_20220927_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_away',
            name='week_number',
            field=models.IntegerField(default=5),
        ),
    ]
