# Generated by Django 3.2.3 on 2022-10-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_alter_home_away_week_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_away',
            name='week_number',
            field=models.IntegerField(default=7),
        ),
    ]
